# RAW_ENABLE = yes
# TAP_DANCE_ENABLE=yes
# VPATH  +=  keyboards/gboards/
# AUTO_SHIFT_ENABLE = yes # Auto Shift
COMBO_ENABLE=yes
CONSOLE_ENABLE = no

ENCODER_ENABLE = yes
EXTRAFLAGS += -flto
# EXTRAKEY_ENABLE = yes
LTO_ENABLE = yes
# MOUSEKEY_ENABLE = yes
OLED_DRIVER_ENABLE = yes
RGBLIGHT_ENABLE = yes
BOOTMAGIC_ENABLE = lite


#define RGBLIGHT_LAYERS


